# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
    - Release
  pull_request:
    branches:
    - Release

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
-name: Auto Minify
uses: nizarmah/auto-minify@v2.0
  with:
    directory: # optional, default is .
    # Directory that contains the minified files. Defaults to same directory
    output: # optional, default is 
    # Descend at most levels (a non-negative integer) levels of directories below the starting-points.
    maxdepth: # optional, default is 
    # Specifies which of the supported packages minifies JS files.
    js_engine: # optional, default is babel
- name: compress-action
  # You may pin to the exact commit or the version.
  # uses: Charlesworth/compress-action@3d837949305ec61c1ca83ceb55218225d0b96eb6
  uses: Charlesworth/compress-action@1.0.0
  with:
    # directory to target
    target-directory: # default is .
